// Generated by the Nikaia bootstrap compiler (Stage 0).
// Edit the .nika source, not this file.

#[allow(unused_imports)]
pub use nikaia_std::prelude::*;
#[allow(unused_imports)]
pub use nikaia_std::error::Full;

// use std::fs

async fn control() -> Result<(), Box<dyn std::error::Error>> {
    let a = match fs::read_to_string("eins.txt").await {
        Ok(value) => value,
        Err(_error) => { "".to_string() },
    };
    let b = match fs::read_to_string("zwei.txt").await {
        Ok(value) => value,
        Err(_error) => { "".to_string() },
    };
    println!("{} {}", a.len() as i64, b.len() as i64);
    Ok(())
}

async fn foreign_against_foreign() {
    let first = hyper_shim::serve_once(18080);
    let second = hyper_shim::serve_once(18081);
    println!("{} {}", first, second);
}

async fn foreign_against_a_read() -> Result<(), Box<dyn std::error::Error>> {
    let served = hyper_shim::serve_once(18082);
    let file = match fs::read_to_string("eins.txt").await {
        Ok(value) => value,
        Err(_error) => { "".to_string() },
    };
    println!("{} {}", served, file.len() as i64);
    Ok(())
}

async fn a_read_against_foreign() -> Result<(), Box<dyn std::error::Error>> {
    let file = match fs::read_to_string("zwei.txt").await {
        Ok(value) => value,
        Err(_error) => { "".to_string() },
    };
    let served = hyper_shim::serve_once(18083);
    println!("{} {}", file.len() as i64, served);
    Ok(())
}


