// Generated by the Nikaia bootstrap compiler (Stage 0).
// Edit the .nika source, not this file.

use winnow_grammar::grammar;

grammar! {
    grammar Digits {

        pub rule pair -> Pair =
            left:i32 "," right:i32
            -> { Pair { left, right } }
    }
}

#[derive(Debug, Clone)]
pub struct Pair {
    pub left: i32,
    pub right: i32,
}

