// Generated by the Nikaia bootstrap compiler (Stage 0).
// Edit the .nika source, not this file.

use winnow_grammar::grammar;
#[allow(unused_imports)]
pub use nikaia_std::prelude::*;

// use std::text

grammar! {
    grammar Measurements {

        rule NAME -> &'a str =
            s:until(";" | frame_end)
            -> { s }

        rule TENTHS -> i32 =
            neg:"-"? whole:digit{1,2} "." frac:digit
            -> {
                let mut value = 0;
                for d in whole.chars() { value = value * 10 + text::digit_value(d); }
                value = value * 10 + text::digit_value(frac);
                if neg.is_some() { -value } else { value }
            }

        #[frame(boundary = "\n")]
        rule MEASUREMENT -> Reading<'a> =
            name:NAME ";" => temp:TENTHS frame_end
            -> { Reading { name, temp } }

        pub rule file -> Summary =
            folded:par_fold(MEASUREMENT, Summary::new, |acc, m| { acc.record(m) }, Summary::merge)
            -> { folded }
    }
}

#[derive(Debug, Clone)]
pub struct Reading<'a> {
    name: &'a str,
    temp: i32,
}

