// Generated by the Nikaia bootstrap compiler (Stage 0).
// Edit the .nika source, not this file.

#[allow(unused_imports)]
pub use nikaia_std::prelude::*;
#[allow(unused_imports)]
pub use nikaia_std::error::Full;

// use std::fs

// use std::cli

async fn __nikaia_main() -> Result<(), Box<dyn std::error::Error>> {
    let path = nikaia_std::index::or(cli::args().nth(1), || "stock.csv".into());
    let out = nikaia_std::index::or(cli::args().nth(2), || "report.html".into());
    let data = match fs::map(&path).await {
        Ok(value) => value,
        Err(error) => {
            eprintln!("cannot open {}: {}", path, error);
            return Ok(());
        },
    };
    let mut entries = match read(data) {
        Ok(value) => value,
        Err(error) => {
            eprintln!("{}: {}", path, error);
            return Ok(());
        },
    };
    entries.sort_by_key(|entry| { -entry.count });
    let total = total(entries);
    let count = entries.len() as i64;
    let markup = render(entries, total);
    match fs::write(&out, &markup, false, true).await {
        Ok(value) => value,
        Err(error) => {
            eprintln!("cannot write {}: {}", out, error);
            return Ok(());
        },
    };
    println!("{} items, {} in total", count, total);
    Ok(())
}


// ADR-038 D4: the runtime is running before the program's first
// statement, so an operation inside it costs no thread wake-up. What
// starts is what `user_parallelism` allows (ADR-037 D2): the I/O
// worker always, a pool for user code only at `yes`.
fn main() -> Result<(), Box<dyn std::error::Error>> {
    nikaia_std::abort::report_in_nikaia_terms(__NIKAIA_SITES);
    let nikaia_runtime = nikaia_std::rt::start(nikaia_std::rt::UserCode::Sequential);
    let outcome = nikaia_std::rt::exec::block_on(__nikaia_main());
    nikaia_runtime.finish();
    outcome
}


// ADR-044 D1: the generated line, and the `.nika` line it came from.
const __NIKAIA_SITES: &[nikaia_std::abort::Site] = &[
    (9, "examples/inventory/main.nika", 35),
    (11, "examples/inventory/main.nika", 36),
    (13, "examples/inventory/main.nika", 38),
    (14, "examples/inventory/main.nika", 39),
    (15, "examples/inventory/main.nika", 40),
    (16, "examples/inventory/main.nika", 42),
    (19, "examples/inventory/main.nika", 43),
    (20, "examples/inventory/main.nika", 44),
    (23, "examples/inventory/main.nika", 47),
    (26, "examples/inventory/main.nika", 48),
    (27, "examples/inventory/main.nika", 49),
    (30, "examples/inventory/main.nika", 52),
    (31, "examples/inventory/main.nika", 54),
    (32, "examples/inventory/main.nika", 55),
    (33, "examples/inventory/main.nika", 56),
    (34, "examples/inventory/main.nika", 58),
    (37, "examples/inventory/main.nika", 59),
    (38, "examples/inventory/main.nika", 60),
    (41, "examples/inventory/main.nika", 63),
];
