// Generated by the Nikaia bootstrap compiler (Stage 0).
// Edit the .nika source, not this file.

use winnow_grammar::grammar;
#[allow(unused_imports)]
pub use nikaia_std::prelude::*;
#[allow(unused_imports)]
pub use nikaia_std::error::Full;

grammar! {
    grammar Stock {

        rule FIELD -> &'a str =
            s:until(";" | frame_end)
            -> { s }

        rule COUNT -> i64 =
            n:dec<i64>(digit+)
            -> { n }

        #[frame(boundary = "\n")]
        rule ENTRY -> Entry<'a> =
            category:FIELD ";" => item:FIELD ";" count:COUNT frame_end
            -> { Entry { category, item, count } }

        pub rule file -> Vec<Entry<'a>> =
            entries:ENTRY*
            -> { entries }
    }
}

#[derive(Debug, Clone)]
pub struct Entry<'a> {
    pub category: &'a str,
    pub item: &'a str,
    pub count: i64,
}

pub fn read(data: &str) -> Result<Vec<Entry<'_>>, ParseError> {
    let __nikaia_value = {
        use winnow::Parser;
        let _source = &*data;
        let mut stream = winnow_grammar::ParseInput::<()> {
            state: winnow_grammar::ParseContext::<()>::default(),
            input: winnow::stream::LocatingSlice::new(_source),
        };
        Stock::parse_file()
            .parse_next(&mut stream)
            .map_err(|error| ParseError::of(error.render(_source)))
    }?;
    Ok(__nikaia_value)
}

fn weight(entry: &Entry<'_>) -> i64 { entry.count }

pub fn total(entries: &Vec<Entry<'_>>) -> i64 {
    let mut sum = 0;
    for e in entries.iter() { sum += weight(&e); }
    sum
}


