// Generated by the Nikaia bootstrap compiler (Stage 0).
// Edit the .nika source, not this file.


// sync (Part II, 12.1): pure CPU, cannot pause. Checked before
// this was written - see `contracts::sync`.
pub fn digit_value(c: char) -> i32 { c as i32 - 48 }

