// Generated by the Nikaia bootstrap compiler (Stage 0).
// Edit the .nika source, not this file.

use winnow_grammar::grammar;

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Part<'a> {
    pub name: &'a str,
    pub ty: &'a str,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Fun<'a> {
    pub name: &'a str,
    pub generics: &'a str,
    pub calls: Vec<&'a str>,
    pub wheres: &'a str,
    pub pauses: bool,
    pub parts: Vec<Part<'a>>,
    pub result: &'a str,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Rec<'a> {
    pub what: &'a str,
    pub name: &'a str,
    pub parts: Vec<Part<'a>>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Group<'a> {
    pub what: &'a str,
    pub name: &'a str,
    pub via: &'a str,
    pub visible: bool,
    pub items: Vec<Item<'a>>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum Item<'a> {
    Fun(Fun<'a>),
    Rec(Rec<'a>),
    Group(Group<'a>),
    Hidden(Fun<'a>),
    Used(&'a str),
    Export(&'a str),
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum Found<'a> {
    One(Item<'a>),
    Skip,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum Called<'a> {
    One(&'a str),
    Many(Vec<&'a str>),
    Nothing,
}

grammar! {
    grammar Rust {

        rule WSE =
            multispace1
            -> { }

        rule WS =
            (WSE | LINE | BLOCK)*
            -> { }

        rule LINE =
            "//" until(line_ending)
            -> { }

        rule BLOCK =
            "/*" until("*/") "*/"
            -> { }

        pub rule file -> Vec<Item<'a>> =
            items:public eof
            -> { items }

        rule public -> Vec<Item<'a>> =
            found:found*
            -> { kept(found) }

        rule exposed -> Vec<Item<'a>> =
            found:found_exposed*
            -> { kept(found) }

        rule found -> Found<'a> =
            i:item
            -> { Found::One(i) }
          | f:method
            -> { Found::One(Item::Hidden(f)) }
          | JUNK
            -> { Found::Skip }

        rule found_exposed -> Found<'a> =
            f:method
            -> { Found::One(Item::Fun(f)) }
          | i:item
            -> { Found::One(i) }
          | JUNK
            -> { Found::Skip }

        rule item -> Item<'a> =
            f:function
            -> { Item::Fun(f) }
          | r:record
            -> { Item::Rec(r) }
          | g:group
            -> { Item::Group(g) }
          | e:export
            -> { Item::Export(e) }
          | u:import
            -> { Item::Used(u) }

        rule export -> &'a str =
            PUB USE t:USE_TEXT ";"
            -> { t }

        rule import -> &'a str =
            USE t:USE_TEXT ";"
            -> { t }

        rule USE_TEXT -> &'a str =
            s:text(USE_RUN)
            -> { s.trim() }

        rule USE_RUN =
            USE_PIECE+
            -> { }

        rule USE_PIECE =
            not(";") (BRACES | LINE | BLOCK | ANY)
            -> { }

        rule function -> Fun<'a> =
            PUB f:method
            -> { f }

        rule method -> Fun<'a> =
            pauses:qualifiers FN name:IDENT g:generics parts:parameters result:result w:where_clause c:tail
            -> { Fun { name, generics: g, wheres: w, calls: c, pauses, parts, result } }

        rule qualifiers -> bool =
            qs:qualifier*
            -> {
                let mut pauses = false;
                for q in qs.into_iter() { if q { pauses = true; } }
                pauses
            }

        rule qualifier -> bool =
            ASYNC
            -> { true }
          | CONST
            -> { false }
          | UNSAFE
            -> { false }
          | EXTERN abi
            -> { false }

        rule abi =
            string
            -> { }
          | empty
            -> { }

        rule tail -> Vec<&'a str> =
            cs:inside
            -> { cs }
          | ";"
            -> { Vec::new() }

        rule inside -> Vec<&'a str> =
            "{" cs:inside_run "}"
            -> { cs }

        rule inside_run -> Vec<&'a str> =
            pieces:inside_piece*
            -> { joined(pieces) }

        rule inside_piece -> Called<'a> =
            not("}") STRING
            -> { Called::Nothing }
          | not("}") CHAR
            -> { Called::Nothing }
          | not("}") LINE
            -> { Called::Nothing }
          | not("}") BLOCK
            -> { Called::Nothing }
          | not("}") inner:inside
            -> { Called::Many(inner) }
          | not("}") p:CALL
            -> { Called::One(p) }
          | not("}") ANY
            -> { Called::Nothing }

        rule CALL -> &'a str =
            p:text(PATH) TURBOFISH "("
            -> { p }

        rule PATH =
            raw_ident(PATH_TAIL)*
            -> { }

        rule PATH_TAIL =
            "::" raw_ident
            -> { }

        rule TURBOFISH =
            "::" ANGLES
            -> { }
          | empty
            -> { }

        rule parameters -> Vec<Part<'a>> =
            "(" ps:parameter_list ")"
            -> { ps }

        rule parameter_list -> Vec<Part<'a>> =
            head:parameter tail:parameter_tail* COMMA
            -> {
                let mut all = Vec::new();
                all.push(head);
                for p in tail.into_iter() { all.push(p); }
                all
            }
          | empty
            -> { Vec::new() }

        rule parameter_tail -> Part<'a> =
            "," p:parameter
            -> { p }

        rule parameter -> Part<'a> =
            t:text(receiver)
            -> { Part { name: "self", ty: t.trim() } }
          | MUT n:IDENT ":" t:PARAM_TYPE
            -> { Part { name: n, ty: t } }
          | n:IDENT ":" t:PARAM_TYPE
            -> { Part { name: n, ty: t } }
          | n:HOLE ":" t:PARAM_TYPE
            -> { Part { name: n, ty: t } }

        rule receiver =
            "&" LIFETIME MUT SELF
            -> { }
          | "&" LIFETIME SELF
            -> { }
          | "&" MUT SELF
            -> { }
          | "&" SELF
            -> { }
          | MUT SELF
            -> { }
          | SELF
            -> { }

        rule record -> Rec<'a> =
            PUB STRUCT name:IDENT generics where_clause "{" fs:field_list "}"
            -> { Rec { what: "struct", name, parts: fs } }
          | PUB STRUCT name:IDENT generics tuple_body where_clause ";"
            -> { Rec { what: "struct", name, parts: Vec::new() } }
          | PUB ENUM name:IDENT generics where_clause "{" vs:variant_list "}"
            -> { Rec { what: "enum", name, parts: vs } }

        rule tuple_body =
            "(" TUPLE_INNER ")"
            -> { }
          | empty
            -> { }

        rule field_list -> Vec<Part<'a>> =
            head:field tail:field_tail* COMMA
            -> {
                let mut all = Vec::new();
                all.push(head);
                for f in tail.into_iter() { all.push(f); }
                all
            }
          | empty
            -> { Vec::new() }

        rule field_tail -> Part<'a> =
            "," f:field
            -> { f }

        rule field -> Part<'a> =
            PUB n:IDENT ":" t:FIELD_TYPE
            -> { Part { name: n, ty: t } }
          | n:IDENT ":" t:FIELD_TYPE
            -> { Part { name: n, ty: t } }

        rule variant_list -> Vec<Part<'a>> =
            head:variant tail:variant_tail* COMMA
            -> {
                let mut all = Vec::new();
                all.push(head);
                for v in tail.into_iter() { all.push(v); }
                all
            }
          | empty
            -> { Vec::new() }

        rule variant_tail -> Part<'a> =
            "," v:variant
            -> { v }

        rule variant -> Part<'a> =
            n:IDENT t:text(payload)
            -> { Part { name: n, ty: t.trim() } }

        rule payload =
            "(" TUPLE_INNER ")"
            -> { }
          | "{" BRACE_INNER "}"
            -> { }
          | empty
            -> { }

        rule group -> Group<'a> =
            UNSAFE IMPL generics v:IMPL_TYPE FOR t:IMPL_TYPE where_clause "{" items:exposed "}"
            -> { Group { what: "unsafe impl", name: t, via: v, visible: true, items } }
          | UNSAFE IMPL generics t:IMPL_TYPE where_clause "{" items:public "}"
            -> { Group { what: "unsafe impl", name: t, via: "", visible: true, items } }
          | IMPL generics v:IMPL_TYPE FOR t:IMPL_TYPE where_clause "{" items:exposed "}"
            -> { Group { what: "impl", name: t, via: v, visible: true, items } }
          | IMPL generics t:IMPL_TYPE where_clause "{" items:public "}"
            -> { Group { what: "impl", name: t, via: "", visible: true, items } }
          | PUB TRAIT name:IDENT generics where_clause "{" items:exposed "}"
            -> { Group { what: "trait", name, via: "", visible: true, items } }
          | PUB MOD name:IDENT "{" items:public "}"
            -> { Group { what: "mod", name, via: "", visible: true, items } }
          | PUB MOD name:IDENT ";"
            -> { Group { what: "mod", name, via: "", visible: true, items: Vec::new() } }
          | MOD name:IDENT "{" items:public "}"
            -> { Group { what: "mod", name, via: "", visible: false, items } }
          | MOD name:IDENT ";"
            -> { Group { what: "mod", name, via: "", visible: false, items: Vec::new() } }

        rule generics -> &'a str =
            "<" g:text(ANGLE_INNER) ">"
            -> { g.trim() }
          | empty
            -> { "" }

        rule where_clause -> &'a str =
            WHERE w:text(WHERE_RUN)
            -> { w.trim() }
          | empty
            -> { "" }

        rule PARAM_TYPE -> &'a str =
            s:text(PARAM_RUN)
            -> { s.trim() }

        rule PARAM_RUN =
            PARAM_PIECE+
            -> { }

        rule PARAM_PIECE =
            not(",") not(")") SPAN
            -> { }

        rule FIELD_TYPE -> &'a str =
            s:text(FIELD_RUN)
            -> { s.trim() }

        rule FIELD_RUN =
            FIELD_PIECE+
            -> { }

        rule FIELD_PIECE =
            not(",") not("}") SPAN
            -> { }

        rule result -> &'a str =
            "->" t:RESULT_TYPE
            -> { t }
          | empty
            -> { "" }

        rule RESULT_TYPE -> &'a str =
            s:text(RESULT_RUN)
            -> { s.trim() }

        rule RESULT_RUN =
            RESULT_PIECE+
            -> { }

        rule RESULT_PIECE =
            not("{") not(";") not(WHERE) SPAN
            -> { }

        rule WHERE_RUN =
            WHERE_PIECE+
            -> { }

        rule WHERE_PIECE =
            not("{") not(";") SPAN
            -> { }

        rule IMPL_TYPE -> &'a str =
            s:text(IMPL_RUN)
            -> { s.trim() }

        rule IMPL_RUN =
            IMPL_PIECE+
            -> { }

        rule IMPL_PIECE =
            not("{") not(WHERE) not(FOR) SPAN
            -> { }

        rule SPAN =
            (ANGLES | PARENS | BRACKETS | STRING | CHAR | LINE | BLOCK | ANY)
            -> { }

        rule JUNK =
            not("}") (STRING | CHAR | LINE | BLOCK | BRACES | ANY)
            -> { }

        rule BRACES =
            "{" BRACE_INNER "}"
            -> { }

        rule BRACE_INNER =
            BRACE_PIECE*
            -> { }

        rule BRACE_PIECE =
            not("}") (STRING | CHAR | LINE | BLOCK | BRACES | ANY)
            -> { }

        rule PARENS =
            "(" TUPLE_INNER ")"
            -> { }

        rule TUPLE_INNER =
            PAREN_PIECE*
            -> { }

        rule PAREN_PIECE =
            not(")") (STRING | CHAR | LINE | BLOCK | PARENS | BRACES | BRACKETS | ANGLES | ANY)
            -> { }

        rule BRACKETS =
            "[" BRACKET_INNER "]"
            -> { }

        rule BRACKET_INNER =
            BRACKET_PIECE*
            -> { }

        rule BRACKET_PIECE =
            not("]") (STRING | CHAR | LINE | BLOCK | PARENS | BRACES | BRACKETS | ANGLES | ANY)
            -> { }

        rule ANGLES =
            "<" ANGLE_INNER ">"
            -> { }

        rule ANGLE_INNER =
            ANGLE_PIECE*
            -> { }

        rule ANGLE_PIECE =
            not(">") (STRING | CHAR | LINE | BLOCK | PARENS | BRACKETS | ANGLES | ANY)
            -> { }

        rule STRING =
            "\"" (SESC | SPLAIN)* "\""
            -> { }

        rule SESC =
            "\\" any
            -> { }

        rule SPLAIN =
            not("\"") not("\\") any
            -> { }

        rule CHAR =
            "'" (CESC | CPLAIN) "'"
            -> { }

        rule CESC =
            "\\" any
            -> { }

        rule CPLAIN =
            not("'") not("\\") any
            -> { }

        rule ANY =
            any
            -> { }

        rule PUB =
            "pub" not(WORD) not("(")
            -> { }

        rule FN =
            "fn" not(WORD)
            -> { }

        rule ASYNC =
            "async" not(WORD)
            -> { }

        rule CONST =
            "const" not(WORD)
            -> { }

        rule UNSAFE =
            "unsafe" not(WORD)
            -> { }

        rule EXTERN =
            "extern" not(WORD)
            -> { }

        rule STRUCT =
            "struct" not(WORD)
            -> { }

        rule ENUM =
            "enum" not(WORD)
            -> { }

        rule TRAIT =
            "trait" not(WORD)
            -> { }

        rule IMPL =
            "impl" not(WORD)
            -> { }

        rule MOD =
            "mod" not(WORD)
            -> { }

        rule FOR =
            "for" not(WORD)
            -> { }

        rule WHERE =
            "where" not(WORD)
            -> { }

        rule MUT =
            "mut" not(WORD)
            -> { }

        rule USE =
            "use" not(WORD)
            -> { }

        rule SELF =
            "self" not(WORD)
            -> { }

        rule WORD =
            alpha1
            -> { }
          | digit
            -> { }
          | "_"
            -> { }

        rule IDENT -> &'a str =
            s:raw_ident
            -> { s }

        rule HOLE -> &'a str =
            s:text("_")
            -> { s }

        rule LIFETIME =
            "'" raw_ident
            -> { }

        rule COMMA =
            ","
            -> { }
          | empty
            -> { }
    }
}

fn joined(pieces: Vec<Called<'_>>) -> Vec<&str> {
    let mut all = Vec::new();
    for piece in pieces.into_iter() {
        match piece {
            Called::One(one) => { all.push(one) },
            Called::Many(many) => { for one in many.iter() { all.push(one); } },
            Called::Nothing => { },
        };
    }
    all
}

fn kept(found: Vec<Found<'_>>) -> Vec<Item<'_>> {
    let mut all = Vec::new();
    for f in found.into_iter() {
        match f {
            Found::One(item) => { all.push(item) },
            Found::Skip => { },
        };
    }
    all
}

